# Generated by Django 5.0 on 2023-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_phonenumbwe_contact_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskrsignup',
            name='education',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
