# Generated by Django 5.0 on 2023-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_jobskrsignup_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskrsignup',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
