# Generated by Django 5.0 on 2023-12-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_jobskrsignup_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workmode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
